apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"helm-guestbook","app.kubernetes.io/instance":"helm-guestbook","chart":"helm-guestbook-0.1.0","heritage":"Helm","release":"helm-guestbook"},"name":"helm-guestbook","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"helm-guestbook","release":"helm-guestbook"},"type":"ClusterIP"}}
  creationTimestamp: '2024-11-30T10:25:50Z'
  labels:
    app: helm-guestbook
    app.kubernetes.io/instance: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: helm-guestbook
  name: helm-guestbook
  namespace: default
  resourceVersion: '78671'
  uid: 50b72d61-1ca3-46e3-953b-2ad142863877
spec:
  clusterIP: 10.110.4.213
  clusterIPs:
    - 10.110.4.213
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: helm-guestbook
    release: helm-guestbook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}